
flib_version=0.2.10
flib_file=8704177

mod_id=scaffoldingpower
curse_id=370777
mod_version=1.4.0
curse_slug=scaffolding-behavior
mod_description=
mod_name=scaffoldingpower
mod_group_id=com.lothrazar.scaffoldingpower
mod_license=SeeGithub
mod_authors=Lothrazar
modrinth_id=scaffolding-behavior